package compute

import (
	"fmt"
	"strings"
)

// InstallScript is the shell script a new machine runs to become a compute:
// it fetches the kernel from the Compa host that issued the token (checked
// against sha256), enrolls with the one-time token, connects the free model
// providers if the machine has no model setup, and keeps `compute serve`
// running under systemd when it can. Everything it needs comes from the host,
// so there is nothing to download from anywhere else.
func InstallScript(baseURL, token, kernelSHA256 string) string {
	r := strings.NewReplacer("@BASE@", shellQ(baseURL), "@TOKEN@", shellQ(token), "@SHA@", shellQ(kernelSHA256))
	return r.Replace(installTemplate)
}

func shellQ(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// InstallCommand is the one line that runs InstallScript from the host.
func InstallCommand(baseURL, token string) string {
	return fmt.Sprintf("curl -fsSL %s | sh", shellQ(strings.TrimRight(baseURL, "/")+"/api/compute/install.sh?token="+token))
}

const installTemplate = `#!/bin/sh
# Makes this machine a compute for Compa: installs the Compa kernel, enrolls it,
# and keeps it serving. Generated by the Compa host; read it before you run it.
set -eu

BASE=@BASE@
TOKEN=@TOKEN@
WANT_SHA=@SHA@

os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)
case "$arch" in
  x86_64|amd64) arch=amd64 ;;
  aarch64|arm64) arch=arm64 ;;
esac

bin="${COMPA_BIN_DIR:-$HOME/.local/bin}"
mkdir -p "$bin"
tmp="$bin/compa-kernel.new"

echo "Fetching the Compa kernel from $BASE ..."
curl -fsSL "$BASE/api/compute/kernel?token=$TOKEN&os=$os&arch=$arch" -o "$tmp"

if command -v sha256sum >/dev/null 2>&1; then
  got=$(sha256sum "$tmp" | cut -d' ' -f1)
else
  got=$(shasum -a 256 "$tmp" | cut -d' ' -f1)
fi
if [ "$got" != "$WANT_SHA" ]; then
  rm -f "$tmp"
  echo "The downloaded kernel does not match the checksum the host announced; not installing." >&2
  exit 1
fi
chmod +x "$tmp"
mv "$tmp" "$bin/compa-kernel"
PATH="$bin:$PATH"
export PATH

compa-kernel compute enroll --url "$BASE" --token "$TOKEN"

home="${COMPA_HOME:-$HOME/.compa}"
if [ ! -f "$home/config.json" ]; then
  echo "No model setup on this machine yet: connecting the free model providers."
  compa-kernel model auto-free || echo "Could not connect free providers; set a model with: compa-kernel model"
fi

if command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
  unit="$HOME/.config/systemd/user"
  mkdir -p "$unit"
  cat > "$unit/compa-compute.service" <<UNIT
[Unit]
Description=Compa compute (serves Compitas for $BASE)

[Service]
ExecStart=$bin/compa-kernel compute serve
Restart=always
RestartSec=5
Environment=PATH=$bin:/usr/local/bin:/usr/bin:/bin

[Install]
WantedBy=default.target
UNIT
  systemctl --user daemon-reload || true
  if systemctl --user enable --now compa-compute.service; then
    echo "Serving. It restarts by itself; to keep it running when you log out: loginctl enable-linger $USER"
    echo "Status: systemctl --user status compa-compute"
  else
    echo "Installed, but the service did not start. Run it yourself and keep it running:"
    echo "  $bin/compa-kernel compute serve"
  fi
else
  echo "Installed. Keep this running (tmux, nohup, or your service manager):"
  echo "  $bin/compa-kernel compute serve"
fi
`
